### ISSUE TITLE
Countdown widget update block page layout modification

### ISSUE THREAD

**Issue by Bacdol** [metinsaylan/wordpress-countdown-widget#10]
Hi,

we use countdown widget since a long time on our wordpress blog without any problem, but the last widget updates generate one bug into our back office and more precisely into the page layout modification interface.

If I use the 2.5.9 version I haven't any problem but if I make the update to 2.6.* version it blocks my page layout modification interface and I can't edit existing widgets (if I deactivated the plugin it works well).

For the moment we keep the 2.5.9 version but it would be great if you can fix this conflict in order to enable us to upgrade your widget to the last version.

Our Wordpress configuration : 
Wordpress version : 4.7.5
Theme : SmartMag version 2.6.2

You can see below an attached file of the bug : 
![capture d ecran 2017-06-02 a 15 28 22](https://cloud.githubusercontent.com/assets/2471575/26727767/405db362-47a8-11e7-87cc-da7eaf63114f.png)

Regards

**Comment by metinsaylan** [comment]
This is probably a conflict with other page builder plugin. Need more details in order to solve this issue.
