### ISSUE TITLE
Language question

### ISSUE THREAD

**Issue by boschj** [metinsaylan/wordpress-countdown-widget#11]
Hi, does the widget enable to change the language of "hours" "minutes" ... ?

If not, a good option would be to enable it, without avoiding to translate the whole widget to evey language, each user could customize it.

**Comment by metinsaylan** [comment]
I am thinking of adding this feature with the next release.

**Comment by metinsaylan** [comment]
Hello @boschj, This feature is added with version 3.1 if you are still interested :) Best.
