### ISSUE TITLE
Just updated to ver 3.0 and it killed the website

### ISSUE THREAD

**Issue by MarcFuller** [metinsaylan/wordpress-countdown-widget#17]
Just updated to the new version and below is the result! It is all that show on any/every page.

Please correct or advise.

    Warning: require_once(countdown-options.php): failed to open stream: No such file or directory in /home/coloradr/public_html/cr/wp-content/plugins/wordpress-countdown-widget/countdown-widget.php on line 45

    Fatal error: require_once(): Failed opening required ‘countdown-options.php’ (include_path=’.:/opt/alt/php71/usr/share/pear’) in /home/coloradr/public_html/cr/wp-content/plugins/wordpress-countdown-widget/countdown-widget.php on line 45

**Comment by metinsaylan** [comment]
Hello Marc, I replied this on WP support forum. Released version 3.1 to address this issue. Thanks.

**Comment by MarcFuller** [comment]
Thank you! Worked great!
