### ISSUE TITLE
Language traNSLATE

### ISSUE THREAD

**Issue by logovacky** [metinsaylan/wordpress-countdown-widget#19]
Hell i need  translate Months/ Month / Days/ Day etc in this plugin here is auto transalte ( czech republic) but translate work  only for singular .. i need complete my transatae thy (im not programator easy on me thy )

**Comment by metinsaylan** [comment]
Hello, you can translate all labels on version 3.1 using option fields under settings. 
![countdown-widget-options-translation](https://user-images.githubusercontent.com/8416919/39666553-23749562-50ae-11e8-9998-aed8b504f709.PNG)
