### ISSUE TITLE
Countdown Widget mobile responsivity

### ISSUE THREAD

**Issue by rakkitehti** [metinsaylan/wordpress-countdown-widget#20]
Hello Metin!

Thank you for this widget. Is there a way to adjust the width of countdown timer on mobile?
I have the timer embedded in my header title with a shortcode.

Thank you

**Comment by metinsaylan** [comment]
Hello @rakkitehti, you can accomplish this by using custom css below:
```
/* Set default width first */
.countdown.hasCountdown{ 
    width: 400px; 
    border: 4px solid #ccc; 
    border-radius: 6px 
}

/* Responsive width for widget */
@media screen and (max-width: 600px) {
    .countdown.hasCountdown{
        background-color: #def;
        width: 200px;
    }
}
```

See demonstration on codepen: https://codepen.io/metinsaylan/pen/VdaXvR
