### ISSUE TITLE
Translation issue Countdown-widget Wordpress

### ISSUE THREAD

**Issue by janjaapkleine** [metinsaylan/wordpress-countdown-widget#27]
Hi there,

First of all, thank you for your great job on the countdown widget. Looks good and easy in use.

In the widget there is a translation issue which is not working properly. Some words like 'hours' and 'minutes' are being translated, but the rest isn't. The only word that is translated correct (to Dutch) is 'minutes' (minuten). The word 'Hours' is translated to 'opening hours' (openingstijden) which means in dutch the hours that a shop is open for business. I would like to give every word the right translation. If it needs to be done in the code, I would like to help you whit that. If it refers to a translation within Wordpress, I would like to know i can find it (so maybe you can help me).

Please let me know if I can do something or if you can help me.

Keep up the good work!

Janjaap

**Comment by metinsaylan** [comment]
Hello, plugin has an options page to allow translations. Please check that page, and see if that helps.

**Comment by janjaapkleine** [comment]
Great, thank you very much!
